import bcrypt from 'bcryptjs';

const passwordHash = bcrypt.hashSync('demo1234', 10);

export const SEED_USERS = [
  // PRODUCERS (8)
  {
    id: 'prod-1',
    name: 'Sarah Jenkins',
    email: 'sarah@greenbean.com',
    passwordHash,
    role: 'PRODUCER',
    orgName: 'GreenBean Cafe & Bakery',
    address: '142 Mercer St, New York, NY 10012',
    lat: 40.7230,
    lng: -73.9985,
    phone: '+1 212-555-0101',
  },
  {
    id: 'prod-2',
    name: 'Marcus Vance',
    email: 'marcus@roasterschoice.com',
    passwordHash,
    role: 'PRODUCER',
    orgName: 'Roasters Choice Coffee',
    address: '88 Spring St, New York, NY 10012',
    lat: 40.7242,
    lng: -73.9968,
    phone: '+1 212-555-0102',
  },
  {
    id: 'prod-3',
    name: 'Elena Rostova',
    email: 'elena@craftharvest.com',
    passwordHash,
    role: 'PRODUCER',
    orgName: 'Craft Harvest Bistro',
    address: '310 W Broadway, New York, NY 10013',
    lat: 40.7208,
    lng: -74.0042,
    phone: '+1 212-555-0103',
  },
  {
    id: 'prod-4',
    name: 'David Chen',
    email: 'david@artisanbakery.com',
    passwordHash,
    role: 'PRODUCER',
    orgName: 'Artisan Bakery Co',
    address: '55 Prince St, New York, NY 10012',
    lat: 40.7235,
    lng: -73.9958,
    phone: '+1 212-555-0104',
  },
  {
    id: 'prod-5',
    name: 'Rachel Bloom',
    email: 'rachel@urbanmarket.com',
    passwordHash,
    role: 'PRODUCER',
    orgName: 'Urban Market Grocers',
    address: '520 Broadway, New York, NY 10012',
    lat: 40.7248,
    lng: -73.9972,
    phone: '+1 212-555-0105',
  },
  {
    id: 'prod-6',
    name: 'Liam O\'Connor',
    email: 'liam@ecobrew.com',
    passwordHash,
    role: 'PRODUCER',
    orgName: 'EcoBrew Microbrewery',
    address: '180 Lafayette St, New York, NY 10013',
    lat: 40.7212,
    lng: -73.9982,
    phone: '+1 212-555-0106',
  },
  {
    id: 'prod-7',
    name: 'Chef Antoine',
    email: 'antoine@freshtable.com',
    passwordHash,
    role: 'PRODUCER',
    orgName: 'Fresh Table Dining',
    address: '72 Grand St, New York, NY 10013',
    lat: 40.7218,
    lng: -74.0028,
    phone: '+1 212-555-0107',
  },
  {
    id: 'prod-8',
    name: 'Maya Lin',
    email: 'maya@dailyloaf.com',
    passwordHash,
    role: 'PRODUCER',
    orgName: 'Daily Loaf Cafe',
    address: '210 Mulberry St, New York, NY 10012',
    lat: 40.7225,
    lng: -73.9961,
    phone: '+1 212-555-0108',
  },

  // CONSUMERS (6)
  {
    id: 'cons-1',
    name: 'Dr. Aris Thorne',
    email: 'aris@cityfarm.org',
    passwordHash,
    role: 'CONSUMER',
    orgName: 'City Farm Urban Agriculture',
    address: '388 Hudson St, New York, NY 10014',
    lat: 40.7282,
    lng: -74.0078,
    phone: '+1 212-555-0201',
  },
  {
    id: 'cons-2',
    name: 'Carlos Ruiz',
    email: 'carlos@myceliummagic.com',
    passwordHash,
    role: 'CONSUMER',
    orgName: 'Mycelium Magic Mushrooms',
    address: '120 Varick St, New York, NY 10013',
    lat: 40.7265,
    lng: -74.0062,
    phone: '+1 212-555-0202',
  },
  {
    id: 'cons-3',
    name: 'Hannah Abbott',
    email: 'hannah@ecobox.com',
    passwordHash,
    role: 'CONSUMER',
    orgName: 'EcoBox Sustainable Packaging',
    address: '45 Canal St, New York, NY 10002',
    lat: 40.7152,
    lng: -73.9928,
    phone: '+1 212-555-0203',
  },
  {
    id: 'cons-4',
    name: 'Mateo Silva',
    email: 'mateo@verdantcompost.org',
    passwordHash,
    role: 'CONSUMER',
    orgName: 'Verdant Compost Collective',
    address: '500 Grand St, New York, NY 10002',
    lat: 40.7168,
    lng: -73.9855,
    phone: '+1 212-555-0204',
  },
  {
    id: 'cons-5',
    name: 'Clara Oswald',
    email: 'clara@terranova.org',
    passwordHash,
    role: 'CONSUMER',
    orgName: 'Terra Nova Organic Farms',
    address: '150 Delancey St, New York, NY 10002',
    lat: 40.7185,
    lng: -73.9882,
    phone: '+1 212-555-0205',
  },
  {
    id: 'cons-6',
    name: 'Vikram Patel',
    email: 'vikram@bioloop.com',
    passwordHash,
    role: 'CONSUMER',
    orgName: 'BioLoop Energy & Biogas',
    address: '20 Wall St, New York, NY 10005',
    lat: 40.7068,
    lng: -74.0092,
    phone: '+1 212-555-0206',
  },

  // LOGISTICS (1)
  {
    id: 'driver-1',
    name: 'Alex Rivera (Driver)',
    email: 'driver@circularsync.com',
    passwordHash,
    role: 'LOGISTICS',
    orgName: 'Swift Eco Logistics',
    address: '100 Lafayette St, New York, NY 10013',
    lat: 40.7180,
    lng: -74.0010,
    phone: '+1 212-555-0301',
  },

  // ADMIN (1)
  {
    id: 'admin-1',
    name: 'Elena Rostova (Admin)',
    email: 'admin@circularsync.com',
    passwordHash,
    role: 'ADMIN',
    orgName: 'Circular Economy Hub HQ',
    address: '1 World Trade Ctr, New York, NY 10007',
    lat: 40.7128,
    lng: -74.0132,
    phone: '+1 212-555-0401',
  },
];

export const SEED_WASTE_STREAMS = [
  {
    id: 'ws-1',
    producerId: 'prod-1',
    rawDescription: '45kg fresh espresso coffee grounds, clean single-origin arabica substrate',
    wasteType: 'ORGANIC',
    subtype: 'nitrogen_rich',
    quantity: 45.0,
    unit: 'kg',
    frequency: 'DAILY',
    qualityGrade: 'GRADE_A',
    photoUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    pickupReadyAt: new Date(Date.now() + 3600000 * 2).toISOString(),
    status: 'ACTIVE',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'ws-2',
    producerId: 'prod-2',
    rawDescription: '60kg spent coffee chaff and espresso grounds, pure nitrogen compost booster',
    wasteType: 'ORGANIC',
    subtype: 'nitrogen_rich',
    quantity: 60.0,
    unit: 'kg',
    frequency: 'DAILY',
    qualityGrade: 'GRADE_A',
    photoUrl: 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?auto=format&fit=crop&w=600&q=80',
    pickupReadyAt: new Date(Date.now() + 3600000 * 4).toISOString(),
    status: 'ACTIVE',
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 'ws-3',
    producerId: 'prod-3',
    rawDescription: '85kg clean corrugated cardboard boxes, unprinted packaging scraps',
    wasteType: 'CARDBOARD',
    subtype: 'corrugated',
    quantity: 85.0,
    unit: 'kg',
    frequency: 'WEEKLY',
    qualityGrade: 'GRADE_A',
    photoUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=600&q=80',
    pickupReadyAt: new Date(Date.now() + 3600000 * 6).toISOString(),
    status: 'MATCHED',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'ws-4',
    producerId: 'prod-4',
    rawDescription: '30kg stale artisan bread scraps and flour sweepings',
    wasteType: 'ORGANIC',
    subtype: 'bakery_waste',
    quantity: 30.0,
    unit: 'kg',
    frequency: 'DAILY',
    qualityGrade: 'GRADE_B',
    photoUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
    pickupReadyAt: new Date(Date.now() + 3600000 * 1).toISOString(),
    status: 'ACTIVE',
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: 'ws-5',
    producerId: 'prod-5',
    rawDescription: '120kg vegetable trimmings and fruit peels from prep kitchen',
    wasteType: 'ORGANIC',
    subtype: 'produce_waste',
    quantity: 120.0,
    unit: 'kg',
    frequency: 'DAILY',
    qualityGrade: 'GRADE_B',
    photoUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
    pickupReadyAt: new Date(Date.now() + 3600000 * 5).toISOString(),
    status: 'ACTIVE',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'ws-6',
    producerId: 'prod-6',
    rawDescription: '150kg spent barley grain mash from craft brewing batch',
    wasteType: 'ORGANIC',
    subtype: 'brewery_waste',
    quantity: 150.0,
    unit: 'kg',
    frequency: 'BIWEEKLY',
    qualityGrade: 'GRADE_A',
    photoUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=600&q=80',
    pickupReadyAt: new Date(Date.now() + 3600000 * 8).toISOString(),
    status: 'ACTIVE',
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'ws-7',
    producerId: 'prod-7',
    rawDescription: '40kg raw vegetable prep scraps, non-greasy salad waste',
    wasteType: 'ORGANIC',
    subtype: 'produce_waste',
    quantity: 40.0,
    unit: 'kg',
    frequency: 'DAILY',
    qualityGrade: 'GRADE_B',
    photoUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=600&q=80',
    pickupReadyAt: new Date(Date.now() + 3600000 * 3).toISOString(),
    status: 'ACTIVE',
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 'ws-8',
    producerId: 'prod-8',
    rawDescription: '25kg burlap jute coffee bags and natural woven sacks',
    wasteType: 'TEXTILE',
    subtype: 'jute_fiber',
    quantity: 25.0,
    unit: 'kg',
    frequency: 'MONTHLY',
    qualityGrade: 'GRADE_A',
    photoUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
    pickupReadyAt: new Date(Date.now() + 3600000 * 12).toISOString(),
    status: 'ACTIVE',
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: 'ws-9',
    producerId: 'prod-1',
    rawDescription: '35kg organic coffee grounds for oyster mushroom cultivation',
    wasteType: 'ORGANIC',
    subtype: 'nitrogen_rich',
    quantity: 35.0,
    unit: 'kg',
    frequency: 'DAILY',
    qualityGrade: 'GRADE_A',
    photoUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    pickupReadyAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    status: 'COMPLETED',
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: 'ws-10',
    producerId: 'prod-3',
    rawDescription: '90kg heavy corrugated cardboard bales',
    wasteType: 'CARDBOARD',
    subtype: 'corrugated',
    quantity: 90.0,
    unit: 'kg',
    frequency: 'WEEKLY',
    qualityGrade: 'GRADE_A',
    photoUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=600&q=80',
    pickupReadyAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    status: 'COMPLETED',
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
  {
    id: 'ws-11',
    producerId: 'prod-5',
    rawDescription: '110kg mixed supermarket fruit and vegetable leftovers',
    wasteType: 'ORGANIC',
    subtype: 'produce_waste',
    quantity: 110.0,
    unit: 'kg',
    frequency: 'DAILY',
    qualityGrade: 'GRADE_B',
    photoUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
    pickupReadyAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    status: 'COMPLETED',
    createdAt: new Date(Date.now() - 86400000 * 9).toISOString(),
  },
  {
    id: 'ws-12',
    producerId: 'prod-6',
    rawDescription: '200kg brewery spent grain for farm feed',
    wasteType: 'ORGANIC',
    subtype: 'brewery_waste',
    quantity: 200.0,
    unit: 'kg',
    frequency: 'BIWEEKLY',
    qualityGrade: 'GRADE_A',
    photoUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=600&q=80',
    pickupReadyAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    status: 'COMPLETED',
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
];

export const SEED_RESOURCE_NEEDS = [
  {
    id: 'rn-1',
    consumerId: 'cons-1',
    acceptedTypes: ['ORGANIC', 'coffee_grounds', 'produce_waste', 'compost'],
    maxRadiusKm: 8.0,
    minVolume: 20.0,
    needWindowFrom: new Date(Date.now() - 86400000).toISOString(),
    needWindowTo: new Date(Date.now() + 86400000 * 5).toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'rn-2',
    consumerId: 'cons-2',
    acceptedTypes: ['ORGANIC', 'coffee_grounds', 'nitrogen_rich', 'mushroom_substrate'],
    maxRadiusKm: 5.0,
    minVolume: 15.0,
    needWindowFrom: new Date(Date.now() - 86400000).toISOString(),
    needWindowTo: new Date(Date.now() + 86400000 * 7).toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'rn-3',
    consumerId: 'cons-3',
    acceptedTypes: ['CARDBOARD', 'corrugated', 'packaging', 'TEXTILE'],
    maxRadiusKm: 12.0,
    minVolume: 50.0,
    needWindowFrom: new Date(Date.now() - 86400000).toISOString(),
    needWindowTo: new Date(Date.now() + 86400000 * 10).toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'rn-4',
    consumerId: 'cons-4',
    acceptedTypes: ['ORGANIC', 'food_scraps', 'produce_waste', 'bakery_waste'],
    maxRadiusKm: 10.0,
    minVolume: 30.0,
    needWindowFrom: new Date(Date.now() - 86400000).toISOString(),
    needWindowTo: new Date(Date.now() + 86400000 * 6).toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'rn-5',
    consumerId: 'cons-5',
    acceptedTypes: ['ORGANIC', 'brewery_waste', 'spent_grain', 'animal_feed'],
    maxRadiusKm: 15.0,
    minVolume: 80.0,
    needWindowFrom: new Date(Date.now() - 86400000).toISOString(),
    needWindowTo: new Date(Date.now() + 86400000 * 14).toISOString(),
    createdAt: new Date().toISOString(),
  },
];

export const SEED_MATCHES = [
  {
    id: 'match-1',
    wasteStreamId: 'ws-1',
    resourceNeedId: 'rn-2',
    score: 94.5,
    compatibilityScore: 100,
    volumeScore: 95,
    distanceScore: 90,
    timingScore: 90,
    reasoning: '94.5% compatibility seal · 1.4km distance, 45kg nitrogen-rich coffee grounds directly matches mushroom substrate demand.',
    status: 'PROPOSED',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'match-2',
    wasteStreamId: 'ws-2',
    resourceNeedId: 'rn-1',
    score: 91.0,
    compatibilityScore: 100,
    volumeScore: 90,
    distanceScore: 85,
    timingScore: 90,
    reasoning: '91.0% compatibility seal · 1.8km distance, 60kg volume fits urban farm soil amendment window.',
    status: 'PROPOSED',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'match-3',
    wasteStreamId: 'ws-3',
    resourceNeedId: 'rn-3',
    score: 96.0,
    compatibilityScore: 100,
    volumeScore: 98,
    distanceScore: 92,
    timingScore: 95,
    reasoning: '96.0% compatibility seal · 2.1km distance, 85kg clean corrugated cardboard ready for eco-packaging re-pulping.',
    status: 'ACCEPTED',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'match-4',
    wasteStreamId: 'ws-9',
    resourceNeedId: 'rn-2',
    score: 98.0,
    compatibilityScore: 100,
    volumeScore: 100,
    distanceScore: 95,
    timingScore: 95,
    reasoning: '98.0% compatibility seal · 1.2km distance, 35kg completed swap.',
    status: 'ACCEPTED',
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: 'match-5',
    wasteStreamId: 'ws-10',
    resourceNeedId: 'rn-3',
    score: 95.0,
    compatibilityScore: 100,
    volumeScore: 95,
    distanceScore: 90,
    timingScore: 92,
    reasoning: '95.0% compatibility seal · 2.4km distance, 90kg cardboard recycled.',
    status: 'ACCEPTED',
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
  {
    id: 'match-6',
    wasteStreamId: 'ws-11',
    resourceNeedId: 'rn-4',
    score: 93.0,
    compatibilityScore: 100,
    volumeScore: 90,
    distanceScore: 90,
    timingScore: 90,
    reasoning: '93.0% compatibility seal · 1.9km distance, 110kg produce composted.',
    status: 'ACCEPTED',
    createdAt: new Date(Date.now() - 86400000 * 9).toISOString(),
  },
];

export const SEED_PICKUP_JOBS = [
  {
    id: 'job-1',
    matchId: 'match-3',
    driverId: 'driver-1',
    status: 'PENDING',
    scheduledDate: new Date().toISOString(),
    routeOrder: 1,
    estimatedTime: new Date(Date.now() + 3600000 * 2).toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'job-2',
    matchId: 'match-4',
    driverId: 'driver-1',
    status: 'DELIVERED',
    scheduledDate: new Date(Date.now() - 86400000 * 6).toISOString(),
    routeOrder: 1,
    estimatedTime: new Date(Date.now() - 86400000 * 6).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: 'job-3',
    matchId: 'match-5',
    driverId: 'driver-1',
    status: 'DELIVERED',
    scheduledDate: new Date(Date.now() - 86400000 * 7).toISOString(),
    routeOrder: 2,
    estimatedTime: new Date(Date.now() - 86400000 * 7).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
];

export const SEED_IMPACT_LOGS = [
  {
    id: 'imp-1',
    matchId: 'match-4',
    co2SavedKg: 17.5,
    waterSavedL: 525.0,
    landfillDivertedKg: 35.0,
    producerSavings: 7.00,
    consumerSavings: 6.30,
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: 'imp-2',
    matchId: 'match-5',
    co2SavedKg: 72.0,
    waterSavedL: 9000.0,
    landfillDivertedKg: 90.0,
    producerSavings: 13.50,
    consumerSavings: 10.80,
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: 'imp-3',
    matchId: 'match-6',
    co2SavedKg: 55.0,
    waterSavedL: 1650.0,
    landfillDivertedKg: 110.0,
    producerSavings: 22.00,
    consumerSavings: 19.80,
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
];

export const SEED_NOTIFICATIONS = [
  {
    id: 'notif-1',
    userId: 'prod-1',
    message: 'GreenBean Cafe → Mycelium Magic: 35kg coffee grounds diverted, 17.5kg CO2 saved!',
    type: 'SWAP_COMPLETED',
    read: false,
    createdAt: new Date(Date.now() - 3600000 * 3).toISOString(),
  },
  {
    id: 'notif-2',
    userId: 'prod-3',
    message: 'New high-score match found! 96.0% compatibility with EcoBox Packaging.',
    type: 'MATCH_PROPOSED',
    read: false,
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
  {
    id: 'notif-3',
    userId: 'driver-1',
    message: 'Pickup job assigned for 85kg corrugated cardboard at Craft Harvest Bistro.',
    type: 'JOB_ASSIGNED',
    read: true,
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
];
